sonar.projectKey=KasandraRamosE_sistema-cursos-frontend
sonar.organization=kasandraramose
sonar.host.url=https://sonarcloud.io
sonar.sources=src
sonar.exclusions=node_modules/**,dist/**,**/*.map,**/*.js.map, **/*.vue.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
