sonar.projectKey=KasandraRamosE_sistema-cursos-frontend
sonar.organization=kasandraramose
sonar.host.url=https://sonarcloud.io
sonar.sources=src
sonar.exclusions=**/*.vue.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info